datasource:
  mysql:
    dev:
      user: root
      password: SaaS.Onine.Mysql-20200323
      net: tcp
      addr: 172.16.10.100
      port: 3306
      schema: cargo
      charset: utf8
      collation: ""
    test:
      user: root
      password: SaaS.Onine.Mysql-20200323
      net: tcp
      addr: 172.16.10.100
      port: 3306
      schema: cargo
      charset: utf8
      collation: ""
    release:
      user: root
      password: SaaS.OnlineXiyang.Mysql-2022
      net: tcp
      addr: 172.16.10.134
      port: 3306
      schema: tms
      charset: utf8
      collation: ""

template:
  - ./templates/default.tmpl

save:
  view:
    path: ../src/main/resources/migration/views
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: R__
    suffix: .sql
  function:
    path: ../src/main/resources/migration/functions
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: R__
    suffix: .sql
  procedure:
    path: ../src/main/resources/migration/procedures
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: R__
    suffix: .sql
  event:
    path: ../src/main/resources/migration/events
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: R__
    suffix: .sql
  table:
    path: ../src/main/resources/migration/tables
    tmpl: '{{ template "table_migration_template" . }}'
    prefix: V__
    suffix: .sql
  ddl:
    path: ../src/main/resources/migration/ddl
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: V__
    suffix: .sql
  dml:
    path: ../src/main/resources/migration/dml
    tmpl: '{{ template "universal_migration_template" . }}'
    prefix: V__
    suffix: .sql